In [1]:
import numpy as np
import cv2

In [2]:
img=cv2.imread('600893.jpg',cv2.IMREAD_COLOR)
# px = img[55,55]
# print(px)

# img[55,55]=[255,255,255]
# px = img[55,55]
# print(px)

In [3]:
# region of image
roi = img[100:150,100:150]
print(roi)
np.shape(roi)

[[[188 187 219]
  [188 187 219]
  [189 188 220]
  ...
  [198 200 224]
  [198 200 224]
  [198 200 224]]

 [[188 187 219]
  [188 187 219]
  [189 188 220]
  ...
  [198 200 224]
  [198 200 224]
  [198 200 224]]

 [[188 187 219]
  [188 187 219]
  [189 188 220]
  ...
  [198 200 224]
  [198 200 224]
  [198 200 224]]

 ...

 [[186 188 219]
  [186 188 219]
  [189 188 220]
  ...
  [198 200 224]
  [198 200 224]
  [198 200 224]]

 [[186 188 219]
  [186 188 219]
  [189 188 220]
  ...
  [198 200 224]
  [198 200 224]
  [198 200 224]]

 [[186 188 219]
  [186 188 219]
  [189 188 220]
  ...
  [198 200 224]
  [198 200 224]
  [198 200 224]]]


(50, 50, 3)

In [4]:
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
# img[100:500,100:500]=[0,0,0]
# cv2.imshow('image',img)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [7]:
watch_face = img[1000:1200,300:500]
img[0:200,0:200]=watch_face
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()